swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Accounts API
      description: API for fetching the list of different accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Account list retrieved successully
          schema:
            $ref: '#/definitions/AccountListResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/:accountId:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API to retrieve the list of transactions from an account ( last month )
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Account list retrieved successully
          schema:
            $ref: '#/definitions/TransactionListResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Account Id not found
        '500':
          description: Internal Server Error
  /transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API to create a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Transaction attributes
          required: true
          schema:
            $ref: '#/definitions/CreatingTransaction'
      produces:
        - application/json
      responses:
        '201':
          description: Creating transaction successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields / Bad Request
        '500':
          description: Internal Server Error
  /transaction/:transactionId:
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/UpdatingTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Updating transaction successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionListResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            accountId:
              type: string
            transactionDetails:
              type: object
              properties:
                type:
                  type: string
                date:
                  type: string
                amount:
                  type: number
                description:
                  type: string
                status:
                  type: string
  CreatingTransaction:
    type: object
    properties:
      accountId:
        type: string
      type:
        type: string
      amount:
        type: number
      description:
        type: string
    required:
      - accountId
      - type
      - amount
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          accountId:
            type: string
  UpdatingTransaction:
    type: object
    properties:
      status:
        type: string
      description:
        type: string
  AccountListResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            accountDetails:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                description:
                  type: string
                amount:
                  type: number